Clock App based on new designs - built with Cloudflare workers
Screenly-Labs/clock-app pull request #6
Opened 2022-09-24 12:42 UTC by iamplugged

Specs:
https://www.figma.com/file/WcusWuWZDmdHVWgQlieqSo/TV-Device?node-id=1868%3A883

2022-09-24 17:20 UTC, vpetersson requested changes

2022-09-24 17:20 UTC, vpetersson commented on src/index.jsx
> +//app.get('*', cache({ cacheName: 'default', cacheControl: 'max-age=43200' }))
Is this left in by design?

2022-09-24 17:20 UTC, vpetersson commented on src/index.jsx
> +// import { cache } from 'hono/cache'
Is this left in by design?

2022-09-24 17:20 UTC, vpetersson commented on wrangler.toml
> +workers_dev = false
URL are missing here.

2022-09-24 17:20 UTC, vpetersson commented on wrangler.toml
> +workers_dev = false
URL is missing here.

2022-09-24 17:20 UTC, vpetersson commented
The required secrets should now be available.

2022-09-26 11:07 UTC, iamplugged commented on src/index.jsx
> +//app.get('*', cache({ cacheName: 'default', cacheControl: 'max-age=43200' }))
Yes, let's see if we can just use browser default caching. We take a decision on it after testing in stage.

2022-09-26 11:08 UTC, iamplugged commented on wrangler.toml
> +workers_dev = false
Updated

2022-09-26 11:08 UTC, iamplugged commented on wrangler.toml
> +workers_dev = false
Updated

2022-09-26 11:14 UTC, vpetersson approved these changes

2022-09-26 11:14 UTC, merged